### ISSUE TITLE
implement audit trail for codeigniter project

### ISSUE THREAD

**Issue by maniratna2019** [firoz-ahmad-likhon/codeigniter-audit-trail#2]
I am trying to track all user activities in my project and save into database. I found your link for audit trail in codeigniter. I followed all the instruction as per link . I added trail.php file inside application/config folder and two files inside application/core folder and enabled $config['audit_enable'] = TRUE in trail.php file; Also I created a table as per the query given in the link. But data is not saved in the newly created table. Now what i am missing?

**Comment by firoz-ahmad-likhon** [comment]
Please do all steps again. Ensure that error reporting is on your application and share if any error message is shown.

**Comment by firoz-ahmad-likhon** [comment]
Please do all steps again. Ensure that error reporting is on your
application and share if any error message is shown.

**Comment by maniratna2019** [comment]
I repeated all the steps. I have added trail.php file in config folder and other two files in core folder.
i also did $config['audit_enable'] = TRUE in config/the trail.php. But user activities is not saved in the database. There are no errors also while updating records

**Comment by firoz-ahmad-likhon** [comment]
Do you have any error? Please ensure that error reporting is on in your
application.

**Comment by maniratna2019** [comment]
i have added following code  for error reporting in index.php:
ini_set('display_errors', 'On');
error_reporting(-1);
define('MP_DB_DEBUG', true);
But its not working.

**Comment by firoz-ahmad-likhon** [comment]
Please send me your index.php here

**Comment by maniratna2019** [comment]
I have attached my index file here with.[index.txt](https://github.com/firoz-ahmad-likhon/codeigniter-audit-trail/files/3612809/index.txt)

**Comment by firoz-ahmad-likhon** [comment]
Is your problem solved yet?

**Comment by manigopal** [comment]
for me also records are not getting inserted into #DB @firoz-ahmad-likhon 

Issue / Error : 

A PHP Error was encountered
Severity: Notice

Message: Undefined property: Category::$auth

Filename: core/MY_DB_mysqli_driver.php

Line Number: 185

Backtrace:

File: C:\xampp\htdocs\ciprojects\sterlingll\application\core\MY_DB_mysqli_driver.php
Line: 185
Function: _error_handler

File: C:\xampp\htdocs\ciprojects\sterlingll\application\core\MY_DB_mysqli_driver.php
Line: 106
Function: trail

File: C:\xampp\htdocs\ciprojects\sterlingll\application\models\admin\Model_category.php
Line: 27
Function: update

File: C:\xampp\htdocs\ciprojects\sterlingll\application\controllers\admin\Category.php
Line: 185
Function: update

File: C:\xampp\htdocs\ciprojects\sterlingll\index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Trying to get property of non-object

Filename: core/MY_DB_mysqli_driver.php

Line Number: 185

Backtrace:

File: C:\xampp\htdocs\ciprojects\sterlingll\application\core\MY_DB_mysqli_driver.php
Line: 185
Function: _error_handler

File: C:\xampp\htdocs\ciprojects\sterlingll\application\core\MY_DB_mysqli_driver.php
Line: 106
Function: trail

File: C:\xampp\htdocs\ciprojects\sterlingll\application\models\admin\Model_category.php
Line: 27
Function: update

File: C:\xampp\htdocs\ciprojects\sterlingll\application\controllers\admin\Category.php
Line: 185
Function: update

File: C:\xampp\htdocs\ciprojects\sterlingll\index.php
Line: 315
Function: require_once

A Database Error Occurred
Error Number: 1048

Column 'user_id' cannot be null

INSERT INTO `user_audit_trails` (`user_id`, `event`, `table_name`, `old_values`, `new_values`, `url`, `ip_address`, `user_agent`, `created_at`) VALUES (NULL, 'update', 'categories_info', '{\"status\":\"Disable\"}', '{\"status\":\"Enable\"}', 'admin/category/edit/19', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36', '2020-03-21 15:18:10')

Filename: C:/xampp/htdocs/ciprojects/sterlingll/system/database/DB_driver.php

Line Number: 691

**Comment by manigopal** [comment]
fixed the above issue 

'user_id' => $this->CI->session->id,

modifying above value in file, Core->MY_DB_mysqli_driver.php   around line 185

**Comment by engr-srahman** [comment]
Field value is not saved. How to resolve it ?

**Comment by sicksand** [comment]
HI,
I'm using IonAuth, still got the error of user_id is null.

have change the value to 

'user_id' => $this->CI->session->userdata('id'),
